### ISSUE TITLE
Exception if yml version not recognised

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#10]
I had `version: 0.12.0.dev99999999999999` in my yaml, and it died.

```
$ moban
Traceback (most recent call last):
  File "/bin/moban", line 11, in <module>
    load_entry_point('moban', 'console_scripts', 'moban')()
  File "/.../moban/main.py", line 33, in main
    handle_moban_file(options)
  File "/.../moban/main.py", line 106, in handle_moban_file
    constants.MESSAGE_FILE_VERSION_NOT_SUPPORTED % version)
TypeError: %d format: a number is required, not str
```

Very low priority to fix this ;-)
The error should mention that the moban file format version is not recognised, so it is clear that moban is using the `version` key and nobody else can use it.

**Comment by jayvdb** [comment]
sortof related ... you can see on https://github.com/coala/coala-bears/pull/2134 that I am avoiding creating a second YAML file, however this means that the `version: ..` for the file format conflicts with some of the templates (e.g. [`conf.py.jj2`](https://github.com/moremoban/setupmobans/blob/master/templates/conf.py.jj2#L31) which expect `version` is something else.

I'm not asking you to support my hack... ;-)
