### ISSUE TITLE
CONTRIBUTORS.rst missing from v0.3.4

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#137]
CONTRIBUTORS.rst missing from pypi source tarball v0.3.4, but it was in 0.3.3

```py
> py2pack generate moban 0.3.4
mv moban.spegenerating spec file for moban...
c pTraceback (most recent call last):
  File "setup.py", line 181, in <module>
    long_description=read_files(*FILES),
  File "setup.py", line 134, in read_files
    content = read(single_file)
  File "setup.py", line 142, in read
    with codecs.open(the_relative_file, 'r', 'utf-8') as opened_file:
  File "/usr/lib64/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/metaextract_hryxlriq/moban-0.3.4/CONTRIBUTORS.rst'
yTraceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/metaextract/utils.py", line 105, in _setup_py_run_from_dir
    subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)
  File "/usr/lib64/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/usr/bin/python3 setup.py -q --command-packages metaextract metaextract -o /tmp/tmprphmio21 ' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/py2pack", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/py2pack/__init__.py", line 341, in main
    args.func(args)
  File "/usr/lib/python3.6/site-packages/py2pack/__init__.py", line 243, in generate
    _augment_data_from_tarball(args, tarball_file[0], data)
  File "/usr/lib/python3.6/site-packages/py2pack/__init__.py", line 148, in _augment_data_from_tarball
    data_archive = meta_utils.from_archive(filename)
  File "/usr/lib/python3.6/site-packages/metaextract/utils.py", line 134, in from_archive
    data = _setup_py_run_from_dir(root_dir, py_interpreter)
  File "/usr/lib/python3.6/site-packages/metaextract/utils.py", line 109, in _setup_py_run_from_dir
    subprocess.check_output(cmd, shell=True)
  File "/usr/lib64/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/usr/bin/python3 setup.py -q --command-packages metaextract metaextract -o /tmp/tmprphmio21 ' returned non-zero exit status 1.
```

**Comment by chfw** [comment]
I am sorry for the show stopper. 

The problem has bite me twice now: Manifest.in.jj2 without CONTRIBUTORS.rst overrided the output file.
