### ISSUE TITLE
file permission transfer from source template won't work on windows

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#141]
```
2018-12-10T22:33:56.0900746Z ======================================================================
2018-12-10T22:33:56.0900924Z FAIL: Save as above, but this time,
2018-12-10T22:33:56.0901119Z ----------------------------------------------------------------------
2018-12-10T22:33:56.0901293Z Traceback (most recent call last):
2018-12-10T22:33:56.0901495Z   File "c:\hostedtoolcache\windows\python\3.7.0\x64\lib\site-packages\nose\case.py", line 198, in runTest
2018-12-10T22:33:56.0901676Z     self.test(*self.arg)
2018-12-10T22:33:56.0901864Z   File "D:\a\1\s\tests\test_hash_store.py", line 94, in test_dest_file_file_permision_changed
2018-12-10T22:33:56.0902217Z     assert flag is True
2018-12-10T22:33:56.0902393Z AssertionError

```
https://dev.azure.com/moremoban/moban/_build/results?buildId=16

**Comment by chfw** [comment]
@jayvdb , what your opinion on permission transfer on windows os? 

I would say no to transfer unix file permission to windows file when apply unix based repo on windows files.
