### ISSUE TITLE
templating a directory fails on windows.

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#142]
```
2018-12-10T22:45:26.8781847Z ERROR: test_docs.TestTutorial.test_level_8
2018-12-10T22:45:26.8796066Z ----------------------------------------------------------------------
2018-12-10T22:45:26.8917405Z Traceback (most recent call last):
2018-12-10T22:45:26.8922859Z   File "c:\hostedtoolcache\windows\python\3.7.0\x64\lib\site-packages\nose\case.py", line 198, in runTest
2018-12-10T22:45:26.8928335Z     self.test(*self.arg)
2018-12-10T22:45:26.8928650Z   File "D:\a\1\s\tests\test_docs.py", line 93, in test_level_8
2018-12-10T22:45:26.8928723Z     self._raw_moban(["moban"], folder, expected, check_file)
2018-12-10T22:45:26.8928788Z   File "D:\a\1\s\tests\test_docs.py", line 123, in _raw_moban
2018-12-10T22:45:26.8928984Z     main()
2018-12-10T22:45:26.8929059Z   File "D:\a\1\s\moban\main.py", line 36, in main
2018-12-10T22:45:26.8929141Z     count = handle_moban_file(moban_file, options)
2018-12-10T22:45:26.8929205Z   File "D:\a\1\s\moban\main.py", line 121, in handle_moban_file
2018-12-10T22:45:26.8929290Z     mobanfile.handle_moban_file_v1(moban_file_configurations, options)
2018-12-10T22:45:26.8929363Z   File "D:\a\1\s\moban\mobanfile.py", line 61, in handle_moban_file_v1
2018-12-10T22:45:26.8929552Z     number_of_templated_files = handle_targets(merged_options, targets)
2018-12-10T22:45:26.8929619Z   File "D:\a\1\s\moban\mobanfile.py", line 114, in handle_targets
2018-12-10T22:45:26.8929683Z     engine.render_to_files(jobs_for_each_engine[template_type])
2018-12-10T22:45:26.8929768Z   File "D:\a\1\s\moban\plugins.py", line 81, in render_to_files
2018-12-10T22:45:26.8929832Z     self._render_with_finding_data_first(sta.data_file_index)
2018-12-10T22:45:26.8929911Z   File "D:\a\1\s\moban\plugins.py", line 105, in _render_with_finding_data_first
2018-12-10T22:45:26.8930645Z     template = self.engine.get_template(template_file)
2018-12-10T22:45:26.8930708Z   File "D:\a\1\s\moban\jinja2\engine.py", line 94, in get_template
2018-12-10T22:45:26.8930786Z     template = self.jj2_environment.get_template(template_file)
2018-12-10T22:45:26.8930860Z   File "c:\hostedtoolcache\windows\python\3.7.0\x64\lib\site-packages\jinja2\environment.py", line 830, in get_template
2018-12-10T22:45:26.8930946Z     return self._load_template(name, self.make_globals(globals))
2018-12-10T22:45:26.8931020Z   File "c:\hostedtoolcache\windows\python\3.7.0\x64\lib\site-packages\jinja2\environment.py", line 804, in _load_template
2018-12-10T22:45:26.8931135Z     template = self.loader.load(self, name, globals)
2018-12-10T22:45:26.8931206Z   File "c:\hostedtoolcache\windows\python\3.7.0\x64\lib\site-packages\jinja2\loaders.py", line 113, in load
2018-12-10T22:45:26.8931395Z     source, filename, uptodate = self.get_source(environment, name)
2018-12-10T22:45:26.8931588Z   File "c:\hostedtoolcache\windows\python\3.7.0\x64\lib\site-packages\jinja2\loaders.py", line 168, in get_source
2018-12-10T22:45:26.8931661Z     pieces = split_template_path(template)
2018-12-10T22:45:26.8931745Z   File "c:\hostedtoolcache\windows\python\3.7.0\x64\lib\site-packages\jinja2\loaders.py", line 31, in split_template_path
2018-12-10T22:45:26.8931808Z     raise TemplateNotFound(template)
2018-12-10T22:45:26.8931879Z jinja2.exceptions.TemplateNotFound: templates\my.jj2
```

**Comment by chfw** [comment]
https://github.com/moremoban/moban/commit/3bed5df0f6de25051fd01d5b5b20771be29b4869
