### ISSUE TITLE
Cyclic test dependencies

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#156]
- moban tests depends on moban-handlebars (according to `tests/requirements.txt`)
- moban-handlebars tests depends on moban (according to its `tests/requirements.txt`)

This creates a problem for RPM packaging, as the build process for an RPM includes a `%check` which needs to be run before the RPM is finalised, and it only has `BuildRequires` so it can not have separate sets of build & test dependencies.

Currently the solution would be to add a patch which removes moban-handlebars from the moban test suite.

**Comment by jayvdb** [comment]
The tests also depend on packages `pypi-mobans-pkg` and `pip` , and on `git`, and there are two more errors at

https://build.opensuse.org/package/live_build_log/home:jayvdb:soe/python-moban/openSUSE_Tumbleweed/i586

**Comment by chfw** [comment]
moban-handlebars is needed for the doc tests. For moban's ci, it is good to have it. So need to think further how to resolve it.

```
======================================================================
ERROR: test_docs.TestTutorial.test_level_11
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/jaska/github/moremoban/moban/tests/test_docs.py", line 108, in test_level_11
    self._raw_moban(["moban"], folder, expected, "a.output")
  File "/Users/jaska/github/moremoban/moban/tests/test_docs.py", line 124, in _raw_moban
    main()
  File "/Users/jaska/github/moremoban/moban/moban/main.py", line 36, in main
    count = handle_moban_file(moban_file, options)
  File "/Users/jaska/github/moremoban/moban/moban/main.py", line 121, in handle_moban_file
    mobanfile.handle_moban_file_v1(moban_file_configurations, options)
  File "/Users/jaska/github/moremoban/moban/moban/mobanfile.py", line 79, in handle_moban_file_v1
    number_of_templated_files = handle_targets(merged_options, targets)
  File "/Users/jaska/github/moremoban/moban/moban/mobanfile.py", line 132, in handle_targets
    engine.render_to_files(jobs_for_each_engine[template_type])
  File "/Users/jaska/github/moremoban/moban/moban/plugins.py", line 83, in render_to_files
    self._render_with_finding_data_first(sta.data_file_index)
  File "/Users/jaska/github/moremoban/moban/moban/plugins.py", line 112, in _render_with_finding_data_first
    template_abs_path, template, data, output
  File "/Users/jaska/github/moremoban/moban/moban/plugins.py", line 64, in apply_template
    template, data, output_file
  File "/Users/jaska/github/moremoban/moban/moban/jinja2/engine.py", line 109, in apply_template
    rendered_content = template.render(**data)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/jaska/github/moremoban/moban/docs/level-11-use-handlebars/a.template.handlebars", line 1, in top-level template code
    {{no-inheritance}}
jinja2.exceptions.UndefinedError: 'no' is undefined
```

**Comment by jayvdb** [comment]
Yup, ill fix the mako problem now.

**Comment by jayvdb** [comment]
afaics, we cant (easily) install extra packages into the real system, and the tests run on the real system rather than the build root.

So I worked around those by `nosetests` argument `-e '(test_default_mako_type|test_level_10)'`

I could do the same to workaround `test_level_11`, to break the cyclic dependency for `moban-handlebars`.

Another approach is to include a real plugin in the moban package, so it is also installed on the real system.

The alternative is to build and release a moban dummy test package (sort of like a devel package), but that feels a bit wrong -- ive seen some very large and important toolkits do this, but I doubt that it should be done by a relatively small/minor package like moban.

The other alternative is to use mocks and other hacks in the test suite / docs.  Not sure if that is worth attempting.

**Comment by chfw** [comment]
@jayvdb ， again, I did not realize that package validation is performed live on user's machine. It is agreeable that no user want extra test package is installed.

**Comment by jayvdb** [comment]
fwiw, the package is now accepted to https://build.opensuse.org/package/show/devel:languages:python/python-moban
