### ISSUE TITLE
`requires` doesnt understand local .git directory

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#208]
```
> ~/.local/bin/moban -m mobanfile
Directory '../pypi-mobans/.git' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/home/jayvdb/.local/bin/moban", line 11, in <module>
    load_entry_point('moban', 'console_scripts', 'moban')()
  File "/home/jayvdb/projects/moban/moban/moban/main.py", line 33, in main
    count = handle_moban_file(moban_file, options)
  File "/home/jayvdb/projects/moban/moban/moban/main.py", line 145, in handle_moban_file
    mobanfile.handle_moban_file_v1(moban_file_configurations, options)
  File "/home/jayvdb/projects/moban/moban/moban/mobanfile.py", line 56, in handle_moban_file_v1
    handle_requires(requires)
  File "/home/jayvdb/projects/moban/moban/moban/mobanfile.py", line 186, in handle_requires
    pip_install(pypi_pkgs)
  File "/home/jayvdb/projects/moban/moban/moban/utils.py", line 131, in pip_install
    [sys.executable, "-m", "pip", "install", " ".join(packages)]
  File "/home/jayvdb/.asdf/installs/python/3.6.7/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/jayvdb/.asdf/installs/python/3.6.7/bin/python', '-m', 'pip', 'install', '../pypi-mobans/.git']' returned non-zero exit status 1.
```

This should do a clone in the moban cache, and use its master.

Similar to https://github.com/moremoban/moban/issues/207

Note this is *not* related to https://github.com/moremoban/moban/issues/170 , which is primarily about using a local directory , whatever it contains - usually a modified clone which isnt saved yet, as that is how people will usually do template development.

**Comment by jayvdb** [comment]
This can be solved upstream at https://github.com/retr0h/git-url-parse/issues/11

**Comment by chfw** [comment]
Because it does not have a file protocol plus moban humbly accepts only a few open source sites, hence this issue emerges but can address it.
