### ISSUE TITLE
openSUSE Leap 15 test collection error on Python 3

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#220]
https://build.opensuse.org/package/live_build_log/home:jayvdb:moban/python-moban/openSUSE_Leap_15.0/x86_64
```
[   65s] ERROR: Failure: UnicodeDecodeError ('ascii' codec can't decode byte 0xe6 in position 89: ordinal not in range(128))
[   65s] ----------------------------------------------------------------------
[   65s] Traceback (most recent call last):
[   65s]   File "/usr/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
[   65s]     raise self.exc_val.with_traceback(self.tb)
[   65s]   File "/usr/lib/python3.6/site-packages/nose/plugins/manager.py", line 154, in generate
[   65s]     for r in result:
[   65s]   File "/usr/lib/python3.6/site-packages/nose/plugins/doctests.py", line 264, in loadTestsFromFile
[   65s]     doc = dh.read()
[   65s]   File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
[   65s]     return codecs.ascii_decode(input, self.errors)[0]
[   65s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 89: ordinal not in range(128)
```

**Comment by jayvdb** [comment]
[opensuse_leap_doctest_log.txt](https://github.com/moremoban/moban/files/2839372/opensuse_leap_doctest_log.txt)

**Comment by jayvdb** [comment]
Strange error, possibly a bug in nose.  May need to use the versions in the log file to recreate this oddity.

**Comment by jayvdb** [comment]
My guess is that moban python files are not declaring an encoding, and hitting some bug in older minor releases of Python.

**Comment by jayvdb** [comment]
The complete log (attached) says it is `libpython3_6m1_0-3.6.5-lp150.1.5`

I tested 3.6.5 in https://travis-ci.org/jayvdb/moban/builds/489894834 , and it is green :/
