### ISSUE TITLE
moban 0.4.5 test failures on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#275]
I havent built on openSUSE since 0.3.10, so this probably has been around for a while

```py
[   79s] ======================================================================
[   79s] FAIL: test_command_line_options.test_duplicated_targets_in_moban_file
[   79s] ----------------------------------------------------------------------
[   79s] Traceback (most recent call last):
[   79s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[   79s]     self.test(*self.arg)
[   79s]   File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
[   79s]     return func(*args, **keywargs)
[   79s]   File "/home/abuild/rpmbuild/BUILD/moban-0.4.5/tests/integration_tests/test_command_line_options.py", line 333, in test_duplicated_targets_in_moban_file
[   79s]     assert_raises(SystemExit, main)
[   79s] AssertionError: SystemExit not raised
[   79s] -------------------- >> begin captured stdout << ---------------------
[   79s] Error: setup.py cannot be found
[   79s] Error: setup.py cannot be found
[   79s] Everything is up to date!
```

```py
[   61s] ======================================================================
[   61s] ERROR: tests.mobanfile.test_mobanfile.test_handle_targets_sequence
[   61s] ----------------------------------------------------------------------
[   61s] Traceback (most recent call last):
[   61s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[   61s]     self.test(*self.arg)
[   61s]   File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
[   61s]     return func(*args, **keywargs)
[   61s]   File "/home/abuild/rpmbuild/BUILD/moban-0.4.5/tests/mobanfile/test_mobanfile.py", line 179, in test_handle_targets_sequence
[   61s]     call_args[1][0][0][0],
[   61s] IndexError: list index out of range
```

It can be reproduced by branching https://build.opensuse.org/package/show/home:jayvdb:moban/python-moban and editing the spec to remove "test_duplicated_targets_in_moban_file" and "test_handle_targets_sequence" from the excluded tests.

The only potential cause I am aware of is not including the handlebars plugin.

**Comment by chfw** [comment]
will be fixed in v0.6.0
