### ISSUE TITLE
UnicodeDecodeError in doctests on openSUSE Leap

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#276]
Very likely caused by python modules which do not declare the encoding of the file.
```
[   62s] ERROR: Failure: UnicodeDecodeError ('ascii' codec can't decode byte 0xe6 in position 89: ordinal not in range(128))
[   62s] ----------------------------------------------------------------------
[   62s] Traceback (most recent call last):
[   62s]   File "/usr/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
[   62s]     raise self.exc_val.with_traceback(self.tb)
[   62s]   File "/usr/lib/python3.6/site-packages/nose/plugins/manager.py", line 154, in generate
[   62s]     for r in result:
[   62s]   File "/usr/lib/python3.6/site-packages/nose/plugins/doctests.py", line 264, in loadTestsFromFile
[   62s]     doc = dh.read()
[   62s]   File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
[   62s]     return codecs.ascii_decode(input, self.errors)[0]
[   62s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 89: ordinal not in range(128)
```

https://build.opensuse.org/package/show/home:jayvdb:moban/python-moban

It could be that openSUSE Leap has an older `nose`, or some other dependency than openSUSE Tumbleweed.

**Comment by jayvdb** [comment]
Dup of https://github.com/moremoban/moban/issues/220
