### ISSUE TITLE
TypeError running moban locally on pypi-mobans

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#283]
```console
$ git checkout https://github.com/moremoban/pypi-mobans/
$ cd pypi-mobans
$ git checkout 255752d4
$ python3.7 -m moban -m mobanfile
Cloning sphinx...
Cloning into 'sphinx'...
remote: Enumerating objects: 95043, done.
remote: Total 95043 (delta 0), reused 0 (delta 0), pack-reused 95043
Receiving objects: 100% (95043/95043), 36.28 MiB | 744.00 KiB/s, done.
Resolving deltas: 100% (72370/72370), done.
```
```py
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/moban/__main__.py", line 4, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/moban/main.py", line 36, in main
    count = handle_moban_file(moban_file, options)
  File "/usr/lib/python3.7/site-packages/moban/main.py", line 142, in handle_moban_file
    mobanfile.handle_moban_file_v1(moban_file_configurations, options)
  File "/usr/lib/python3.7/site-packages/moban/mobanfile.py", line 79, in handle_moban_file_v1
    number_of_templated_files = handle_targets(merged_options, targets)
  File "/usr/lib/python3.7/site-packages/moban/mobanfile.py", line 115, in handle_targets
    for file_list in list_of_templating_parameters:
  File "/usr/lib/python3.7/site-packages/moban/utils.py", line 101, in expand_directories
    true_template_file = os.path.join(a_template_dir, template_file)
  File "/usr/lib64/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'CommentedSeq'
```

**Comment by jayvdb** [comment]
I was likely running an old version of mobans - probably the openSUSE official version which is 0.3.8 iirc.  If that is the case, something about the new syntax breaks badly on the old version, which means there was a 'breaking' change, and the moban yaml version should have been incremented.
