### ISSUE TITLE
changing remotes of a repo fails

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#284]
Last fix related is https://github.com/moremoban/moban/issues/271

```
moban> GIT_PAGER=cat git show mobanfile
commit 62c314f4d2ce53446b03b862b8ba80bf458ca9d9 (HEAD -> pin-ruamel-yaml)
Author: John Vandenberg <jayvdb@gmail.com>
Date:   Mon Jul 8 10:21:33 2019 +0700

    :fire: add ruamel-yaml pins to aid installation

    Re-adds Python 3.4 support, broken by ruamel-yaml desupporting it
    in version 0.15.94.
    Also adds minimum version for ruamel-yaml on Python 3.7 and 3.8-dev.
    And avoids newer arrow desupported on Python 3.4.

    Fixes https://github.com/moremoban/moban/issues/274

diff --git a/mobanfile b/mobanfile
index 2360459..c5da095 100644
--- a/mobanfile
+++ b/mobanfile
@@ -1,8 +1,10 @@
 requires:
-   - pypi-mobans-pkg
+  - type: git
+    url: https://github.com/jayvdb/pypi-mobans
+    branch: 201907-fixes
 configuration:
   template_dir:
-    - "setupmobans:templates"
+    - "pypi-mobans:templates"
     - ".moban.d"
   configuration: moban.yml
 targets:
moban> (cd ~/.moban/repos/pypi-mobans/ && git fetch)
From https://github.com/jayvdb/pypi-mobans
 * [new branch]      201907-fixes                 -> origin/201907-fixes
 * [new branch]      badge-branch                 -> origin/badge-branch
 * [new branch]      badges-scm                   -> origin/badges-scm
 * [new branch]      entry_points                 -> origin/entry_points
 * [new branch]      fix-bsd-license              -> origin/fix-bsd-license
 * [new branch]      fix-plugins                  -> origin/fix-plugins
 * [new branch]      init-all                     -> origin/init-all
 * [new branch]      issue_8                      -> origin/issue_8
 * [new branch]      minreqs-comma                -> origin/minreqs-comma
 * [new branch]      optional-scm_host            -> origin/optional-scm_host
 * [new branch]      patch-1                      -> origin/patch-1
 * [new branch]      revert-gitignore-extra-block -> origin/revert-gitignore-extra-block
 * [new branch]      rm-custom_varaibles          -> origin/rm-custom_varaibles
 * [new branch]      setup-python-version-marker  -> origin/setup-python-version-marker
 * [new branch]      setup-shebang                -> origin/setup-shebang
 * [new branch]      sphinx-templates             -> origin/sphinx-templates
 * [new branch]      sphinx-templates-2           -> origin/sphinx-templates-2
 * [new branch]      sync-gitignore               -> origin/sync-gitignore
 * [new branch]      sync-gitignore-2             -> origin/sync-gitignore-2
 * [new branch]      sync-mobans                  -> origin/sync-mobans
 * [new branch]      use-license-template         -> origin/use-license-template
moban> (cd ~/.moban/repos/pypi-mobans/ && git checkout 201907-fixes)
Already on '201907-fixes'
moban> python3 -m moban -m mobanfile
Updating pypi-mobans...
```
```py
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jayvdb/projects/moban/moban/moban/__main__.py", line 4, in <module>
    main()
  File "/home/jayvdb/projects/moban/moban/moban/main.py", line 34, in main
    count = handle_moban_file(moban_file, options)
  File "/home/jayvdb/projects/moban/moban/moban/main.py", line 149, in handle_moban_file
    mobanfile.handle_moban_file_v1(moban_file_configurations, options)
  File "/home/jayvdb/projects/moban/moban/moban/mobanfile/__init__.py", line 61, in handle_moban_file_v1
    handle_requires(requires)
  File "/home/jayvdb/projects/moban/moban/moban/mobanfile/__init__.py", line 210, in handle_requires
    git_clone(git_repos)
  File "/home/jayvdb/projects/moban/moban/moban/repo.py", line 31, in git_clone
    repo.git.checkout(require.branch)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout 201907-fixes
  stderr: 'error: pathspec '201907-fixes' did not match any file(s) known to git'
```

**Comment by jayvdb** [comment]
Again in coala mobans repo, 
```
mobans> git diff
```
```patch
diff --git a/.moban.yaml b/.moban.yaml
index ff21ffa..ccecdc6 100644
--- a/.moban.yaml
+++ b/.moban.yaml
@@ -22,8 +22,8 @@ requires:
   - https://gitlab.com/coala/package_manager
   # https://github.com/Badgerati/Fudge/pull/72
   - type: git
-    url: https://github.com/jayvdb/Fudge
-    branch: rm-trailing-whitespace
+    url: https://github.com/Badgerati/Fudge
+    branch: develop
   - https://github.com/ogrisel/python-appveyor-demo
   - https://github.com/MathieuBuisson/PowerShell-DevOps
   - https://github.com/github/gitignore
```
```
mobans> python3 -m moban
Warning: 'copy:' is deprecated since 0.4.0! Please use 'targets:' instead
Updating pypi-mobans...
Updating package_manager...
Updating Fudge...
```
```py
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jayvdb/projects/moban/moban/moban/__main__.py", line 4, in <module>
    main()
  File "/home/jayvdb/projects/moban/moban/moban/main.py", line 34, in main
    count = handle_moban_file(moban_file, options)
  File "/home/jayvdb/projects/moban/moban/moban/main.py", line 149, in handle_moban_file
    mobanfile.handle_moban_file_v1(moban_file_configurations, options)
  File "/home/jayvdb/projects/moban/moban/moban/mobanfile/__init__.py", line 61, in handle_moban_file_v1
    handle_requires(requires)
  File "/home/jayvdb/projects/moban/moban/moban/mobanfile/__init__.py", line 210, in handle_requires
    git_clone(git_repos)
  File "/home/jayvdb/projects/moban/moban/moban/repo.py", line 31, in git_clone
    repo.git.checkout(require.branch)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout develop
  stderr: 'error: pathspec 'develop' did not match any file(s) known to git'
```

**Comment by jayvdb** [comment]
It isnt fetching the remote branches
```
> (cd /home/jayvdb/.cache/moban/repos/Fudge && git branch)
* rm-trailing-whitespace
(cd /home/jayvdb/.cache/moban/repos/Fudge && git branch --all)
* rm-trailing-whitespace
  remotes/origin/rm-trailing-whitespace
```
