### ISSUE TITLE
raise PR later: fs.zipfs won't close properly 

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#310]
```
import fs
fs.open_fs('zip://I_do_not_exist_.zip')

```

Exception ignored in: <function FS.__del__ at 0x10491cd08>
Traceback (most recent call last):
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/fs/base.py", line 117, in __del__
    self.close()
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/fs/zipfs.py", line 437, in close
    self._zip.close()
AttributeError: 'xxx' object has no attribute '_zip'

**Comment by chfw** [comment]
https://github.com/PyFilesystem/pyfilesystem2/issues/333

**Comment by chfw** [comment]
https://github.com/PyFilesystem/pyfilesystem2/pull/330
