### ISSUE TITLE
Error install template packages using pip on readonly site-packages

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#359]
Running latest yehua with old pypi-mobans-pkg==0.0.5.  yehua and pypi-mobans-pkg are installed into system site-packages , and it blows up.
```
...
Collecting pypi-mobans-pkg==0.0.7
  Downloading https://files.pythonhosted.org/packages/2e/80/3c88852adfe97677cfbbb7c87ad13f185d6eef3ab59880343562a1625eb3/pypi_mobans_pkg-0.0.7-py2.py3-none-any.whl (130kB)
     |████████████████████████████████| 133kB 352kB/s 
Requirement already satisfied: lml in /home/python3.7/lib/python3.7/site-packages (from pypi-mobans-pkg==0.0.7) (0.0.9)
Installing collected packages: pypi-mobans-pkg
  Found existing installation: pypi-mobans-pkg 0.0.5
    Uninstalling pypi-mobans-pkg-0.0.5:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '__init__.py'
Consider using the `--user` option or check the permissions.

Traceback (most recent call last):
  File "/usr/bin/moban", line 11, in <module>
    load_entry_point('moban==0.4.5', 'console_scripts', 'moban')()
  File "/usr/lib/python3.7/site-packages/moban/main.py", line 34, in main
    count = handle_moban_file(moban_file, options)
  File "/usr/lib/python3.7/site-packages/moban/main.py", line 149, in handle_moban_file
    mobanfile.handle_moban_file_v1(moban_file_configurations, options)
  File "/usr/lib/python3.7/site-packages/moban/mobanfile/__init__.py", line 61, in handle_moban_file_v1
    handle_requires(requires)
  File "/usr/lib/python3.7/site-packages/moban/mobanfile/__init__.py", line 207, in handle_requires
    pip_install(pypi_pkgs)
  File "/usr/lib/python3.7/site-packages/moban/utils.py", line 84, in pip_install
    [sys.executable, "-m", "pip", "install", " ".join(packages)]
  File "/usr/lib64/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', 'pypi-mobans-pkg==0.0.7']' returned non-zero exit status 1.
Initialized empty ...
```

It seems to be ok after the exception, and keeps going despite the error, which is a bit odd because the `pypi-mobans-pkg==0.0.7` dependency means it should have failed.

**Comment by chfw** [comment]
Please check File permissions.

**Comment by chfw** [comment]
Or use sudo ?

**Comment by jayvdb** [comment]
I am using yehua. I am not going to use `sudo` to run a project generator.

The file permissions in site-packages are intentionally read-only, so users cant use pip to overwrite system packages.

**Comment by chfw** [comment]
I see. I just picked this line:

>ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '__init__.py'
Consider using the `--user` option or check the permissions.

**Comment by chfw** [comment]
In this case, I think it is down to pip and setuptools to decide which package to be used. Please try to uninstall system level package v0.5.
