### ISSUE TITLE
Travis moban job fails: fs.opener.errors.UnsupportedProtocol: protocol 'git' is not supported

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#368]
https://travis-ci.org/github/jayvdb/moban/jobs/677191165
```py
moban -m mobanfile
2020-04-20 10:56:37,992 - moban.externals.file_system - ERROR - protocol 'git' is not supported
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/externals/file_system.py", line 164, in exists
    with fs.open_fs(dir_name) as the_fs:
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/fs/opener/registry.py", line 226, in open_fs
    default_protocol=default_protocol,
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/fs/opener/registry.py", line 185, in open
    opener = self.get_opener(protocol)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/fs/opener/registry.py", line 128, in get_opener
    "protocol '{}' is not supported".format(protocol)
fs.opener.errors.UnsupportedProtocol: protocol 'git' is not supported
2020-04-20 10:56:37,993 - root - ERROR - protocol 'git' is not supported
```

**Comment by chfw** [comment]
pip install gitfs2
