### ISSUE TITLE
moban should report the directory is missing

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#8]
Running moban on an uninitialised `pyexcel/pyexcel` clone:

`OSError: Both pyexcel.yaml and commons/config/pyexcel.yaml does not exist`

This is a little confusing.
It would be better to identify that `commons` doesnt exist.
And per https://github.com/moremoban/moban/issues/6 , moban should find it automatically!

Also `pyexcel.yml` exists, which may cause the user to wonder if that is related to the problem.

**Comment by jayvdb** [comment]
Likewise if only `commons` exists, running `moban` without `setupmobans` results in:

```
$ moban
Traceback (most recent call last):
  File "/bin/moban", line 11, in <module>
    load_entry_point('moban', 'console_scripts', 'moban')()
  File "/.../moban/main.py", line 37, in main
    handle_moban_file(options)
  File "/.../moban/main.py", line 98, in handle_moban_file
    handle_moban_file_v1(moban_file_configurations, options)
  File "/.../moban/mobanfile.py", line 23, in handle_moban_file_v1
    engine.render_to_files(list_of_templating_parameters)
  File "/.../moban/engine.py", line 55, in render_to_files
    self._render_with_finding_data_first(sta.data_file_index)
  File "/.../moban/engine.py", line 85, in _render_with_finding_data_first
    flag = self._apply_template(template, data, output)
  File "/.../moban/engine.py", line 92, in _apply_template
    rendered_content = template.render(**data).encode('utf-8')
  File "/.../jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/.../jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/.../jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File ".moban.d/setup.py", line 1, in top-level template code
    {% extends 'setup.py.jj2' %}
  File "/.../jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: setup.py.jj2
```

**Comment by chfw** [comment]
Yep, I will fix it.

**Comment by chfw** [comment]
v0.0.8 will report it as the following example output:

<img width="464" alt="screen shot 2017-11-18 at 23 02 33" src="https://user-images.githubusercontent.com/4280312/32985509-9abafafe-ccb4-11e7-8f0f-16e8921925df.png">
